version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: autotag
      POSTGRES_DB: tagged_links
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: alen/autotag-challenge
    depends_on:
      - db
    ports:
      - "1101:1101"
