# port configuration
server:
  applicationConnectors:
    - type: http
      port: 1101
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: autotag

  # the password
  password: admin

  # the JDBC URL
  url: jdbc:postgresql://db:5432/tagged_links

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
